version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
    - npm install
    - pip3 install --upgrade awscli
  pre_build:
    commands:
    - npm test
  post_build:
    commands:
    - rm -r node_modules
    - npm install --production
    - sed -i.bak 's/\$PARTITION\$/'${PARTITION}'/g;s/\$AWS_REGION\$/'${AWS_REGION}'/g;s/\$ACCOUNT_ID\$/'${ACCOUNT_ID}'/g;s/\$PROJECT_ID\$/'${PROJECT_ID}'/g' template-configuration.json
artifacts:
  files:
  - template.yml
  - README.md
  - package.json
  - app.js
  - appspec.yml
  - scripts/*
  - node_modules/**/*
  - public/**/*
  - template-configuration.json